import type { Metadata } from "next";
import { CartProvider } from "@/context/cartcontext";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/header";
import "./globals.css";

export const metadata: Metadata = {
  title: "ByteShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={` antialiased`}>
        <SessionProvider>
          <CartProvider>
            <Header />
            <main className="container mx-auto px-8 mt-10">{children}</main>
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
