import type { Metadata } from "next";
import { Inter, Barlow } from "next/font/google";
import { CartProvider } from "@/context/cartcontext";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/header";
import "./globals.css";
const inter = Inter({
  subsets: ["latin"],
});
const barlow = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  preload: true,
  variable: "--font-barlow",
});
export const metadata: Metadata = {
  title: "ByteShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="min-h-screen ">
      <body className={` antialiased ${inter.className} ${barlow.variable}`}>
        <SessionProvider>
          <CartProvider>
            <Header />
            <main className="container mx-auto mt-10 max-w-[100rem] px-[5dvw] ">
              {children}
            </main>
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
