import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "ByteShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={` antialiased`}>
        <header>
          <nav>
            <Link href="/products">Products</Link>
          </nav>
        </header>
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
